trigger:
- main

pool:
  name: BY-Agent

stages:
  - stage: 'Maven'
    displayName: 'Execution of java-17 and Maven project'
    jobs:
      - job: 'MavenInstallation'
        steps:
        - script: |
            sudo apt update
            sudo apt install maven -y
            sudo apt install openjdk-17-jdk openjdk-17-jre -y
          displayName: 'Installing maven and java'
        condition: succeeded() 
      
      - job: 'MavenJob'
        steps:
        - script: |
            mvn clean install
            mvn test
            mvn deploy
          displayName: "Running maven command"
        - task: PublishTestResults@2
          inputs:
            testResultsFormat: JUnit
            testResultsFiles: '**/TEST-*.xml'
        dependsOn: MavenInstallation
        condition: succeeded()
    condition: succeeded()

  - stage: 'Docker'
    displayName: 'Publish docker images'
    jobs:
      - job: 'Docker_Install'
        steps:
          - script: |
              chmod +x dockerInstallation.sh
              sudo bash ./dockerInstallation.sh
            displayName: "Docker Installation"
        condition: succeeded()    

      - job: 'Docker_Build'
        steps:
          - script: |
              cp /home/dhanusht/.m2/repository/blueyonder/project/devops/0.0.1-SNAPSHOT/devops-0.0.1-SNAPSHOT.jar .
               sudo docker login devopsprojectby.azurecr.io -u devopsProjectBY -p x4L9aO3mln4zeWBlqwuUJ+8S0Dzjs1PHLVGTFS0l6y+ACRB/GbRO
              docker build -t devops-project:acr-v1 .
            displayName: "Building image"
        dependsOn: 'Docker_Install'
        condition: succeeded()

      - job: 'Docker_Run'
        steps:
          - script: |
              docker run devops-project:acr-v1
            displayName: "Running container"
        dependsOn: 'Docker_Build'
        condition: succeeded()

      - job: 'Docker_Push'
        steps:
          - script: |
              docker tag devops-project:acr-v1 devopsprojectby.azurecr.io/devops-project-v1
              docker push devopsprojectby.azurecr.io/devops-project-v1
            displayName: "Pushing image"
        dependsOn: 'Docker_Run'
        condition: succeeded()
    condition: succeeded()